/*
 * LandaEcomm v2.0 - Global vars
 * Copyright (c) 2015 Juarez Gustavo
 *
 * Description:
 *	- Set global vars
 */
 
//-----------------------------------------------
// Global vars
//-----------------------------------------------
var GLOBAL_FORMS = null;
var GLOBAL_ACCTIONS_LST = null;

var GLOBAL_FORM_NAME = 0;
var GLOBAL_FORM_ACTION = 1;
var GLOBAL_FORM_VALIDATION_FLAG = 2;
var GLOBAL_FORM_FIELDS = 3;
var GLOBAL_FORM_FN_HANDLE_ERROR = 4;
var GLOBAL_FORM_FN_HANDLE_CALLBACK = 5;
var GLOBAL_FORM_FN_CALLBACK_PARAMS = 6;
var GLOBAL_FORM_SEND_PARAMS = 7;
var GLOBAL_FORM_URL_API = 8;
var GLOBAL_FORM_FN_BEFORE_SUBMIT = 9;
var GLOBAL_FORM_LAST = 10;

var GLOBAL_FROM_VAL_ERROR_RESULT = null;

var GLOBAL_FIELD_TYPE_NUMBER = 0;
var GLOBAL_FIELD_TYPE_STRING = 1;
var GLOBAL_FIELD_TYPE_BOOLEAN = 2;
var GLOBAL_FIELD_TYPE_LIST = 3;

var GLOBAL_FIELD_INF_TYPE = 0;
var GLOBAL_FIELD_INF_NAME = 1;
var GLOBAL_FIELD_INF_NAME_DISPLAY = 2;
var GLOBAL_FIELD_INF_VAL_FLAG = 3;
var GLOBAL_FIELD_INF_VAL_FN_DEF = 4;
var GLOBAL_FIELD_INF_VAL_FN_ESP = 5;
var GLOBAL_FIELD_INF_VAL_PARAMS = 6;
var GLOBAL_FIELD_INF_LST = 7;
var GLOBAL_FIELD_INF_LST_FN = 8;

var GLOBAL_FIELD_VAL_PARAM_MIN_LENGTH = 0;
var GLOBAL_FIELD_VAL_PARAM_MAX_LENGTH = 1;
var GLOBAL_FIELD_VAL_PARAM_BETWEEN = 2;
var GLOBAL_FIELD_VAL_PARAM_EMAIL = 3;
var GLOBAL_FIELD_VAL_PARAM_NOT_IS_NUMBER = 4;
var GLOBAL_FIELD_VAL_PARAM_NOT_NULL = 5;

var GLOBAL_FIELD_VAL_CODE_EMAIL=0;//INVALID EMAIL
var GLOBAL_FIELD_VAL_CODE_EMPTY=1;//EMPTY VALUE
var GLOBAL_FIELD_VAL_CODE_NOT_IS_A_NUMBER=2;//EMPTY VALUE

var GLOBAL_FORMS_EXIT_ON_ERROR = false;

var GLOBAL_ACCESS_TOKEN = false;
//----------------------------------------------- 